DROP DATABASE IF EXISTS `LMS`;
CREATE DATABASE `LMS`
/*!40100 DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI */
/*!80016 DEFAULT ENCRYPTION='N' */
;
USE `LMS`;
CREATE TABLE `ADDRESS` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `ADDRESS` VARCHAR(50) NOT NULL,
  `ADDRESS2` VARCHAR(50) DEFAULT NULL,
  `DISTRICT` VARCHAR(20) NOT NULL,
  `CITY` VARCHAR(30) NOT NULL,
  `POSTAL_CODE` VARCHAR(10) DEFAULT NULL,
  `COUNTRY` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
CREATE TABLE `PERSON` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `DATE_OF_BIRTH` TIMESTAMP NOT NULL,
  `ADDRESS_ID` INTEGER UNSIGNED NOT NULL,
  `PHONE_NO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_PERSON_ADDRESS` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
CREATE TABLE `BORROWER`(
  `ID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`ID`),
  CONSTRAINT `FK_BORROWER_PERSON` FOREIGN KEY (`ID`) REFERENCES `PERSON` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
CREATE TABLE `STAFF` (
  `ID` INTEGER UNSIGNED NOT NULL,
  `TYPE` ENUM('ADMIN', 'CLERK', 'LIBRARIAN') NOT NULL,
  `SALARY` DOUBLE NOT NULL,
  -- ONLY FOR CLERK    
  `DESK_NO` INTEGER,
  -- ONLY FOR LIBRARIAN
  `OFFICE_NO` INTEGER,
  PRIMARY KEY(`ID`),
  CONSTRAINT `FK_STAFF_PERSON` FOREIGN KEY (`ID`) REFERENCES `PERSON` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
CREATE TABLE BOOK (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(30) NOT NULL,
  `AUTHOR` VARCHAR(20) NOT NULL,
  `SYNOPSIS` TEXT NOT NULL,
  `GENRE` ENUM(
    'FANTASY',
    'FICTION',
    'HISTORICAL',
    'HORROR',
    'KIDS',
    'MYSTERY',
    'ROMANCE',
    'SCIFI',
    'THRILLER',
    'WESTERN'
  ) NOT NULL,
  `IS_ISSUED` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;
CREATE TABLE `LOAN` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `BORROWER_ID` INTEGER UNSIGNED NOT NULL,
  `BOOK_ID` INTEGER UNSIGNED NOT NULL,
  `ISSUER_ID` INTEGER UNSIGNED NOT NULL,
  `ISSUED_DATE` TIMESTAMP NOT NULL,
  `RECEIVER_ID` INTEGER UNSIGNED,
  `RETURN_DATE` TIMESTAMP,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_LOAN_BORROWER` FOREIGN KEY (`BORROWER_ID`) REFERENCES `PERSON` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_LOAN_BOOK` FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_LOAN_ISSUER` FOREIGN KEY (`ISSUER_ID`) REFERENCES `STAFF` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_LOAN_RECEIVER` FOREIGN KEY (`RECEIVER_ID`) REFERENCES `STAFF` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4;